config-version: 3
messages:
  reload: "&aConfiguration successfully reloaded!"
  command-error-syntax: "&cOops... Something went wrong.. Check the syntax of the command!"
  unknown-world-error: "&cYou're trying to change a world that doesn't exist!"
  gamerule-value-change: "&aThe game rule has been successfully changed for &f%world%!"
  difficulty-value-change: "&aThe difficulty has been successfully changed for &f%world%!"
  pvp-mode-change: "&aYou switched pvp mode to &f%value%"
  ticks-per-mob-spawn:
    monsters: "&aYou have successfully set a ticks per monster spawns in &f%world% &ato &f%value%!"
    animals: "&aYou have successfully set a ticks per animal spawns in &f%world% &ato &f%value%!"
    ambient: "&aYou have successfully set a ticks per ambient spawns in &f%world% &ato &f%value%!"
    water-ambient: "&aYou have successfully set a ticks per water ambient spawns in &f%world% &ato &f%value%!"
    water: "&aYou have successfully set a ticks per water mob spawns in &f%world% &ato &f%value%!"
    underground-creature-spawns: "&aYou have successfully set a ticks per underground creature spawns in &f%world% &ato &f%value%!"
    reset: "&aYou have successfully reset ticks per mob spawns in &f%world% &afor all mob types!"
  spawn-limits:
    monsters: "&aYou have successfully set a monster spawn limit in &f%world% &ato &f%value%!"
    animals: "&aYou have successfully set an animal spawn limit in &f%world% &ato &f%value%!"
    ambient: "&aYou have successfully set an ambient spawn limit in &f%world% &ato &f%value%!"
    water-animals: "&aYou have successfully set an animal spawn limit in &f%world% &ato &f%value%!"
    water-ambient: "&aYou have successfully set an ambient spawn limit in &f%world% &ato &f%value%!"
    reset: "&aYou have successfully reset spawn limit in &f%world% &afor all mob types!"
  server-profile:
    - "&6&lServer profile"
    - "&eServer core: &f%core%"
    - "&eOS: &f%os%"
    - "&eArch: &f%arch%"
    - "&eRAM: &f%ram_using%MB / %ram_max%MB"
    - "&eCPU: &f%cpu_using%% / 100%"
    - "&eServer Uptime: &f%uptime% minutes"
    - "&eLoaded chunks count: &f%loaded_chunks_count%"
  world-profile:
    - "&6&lWorld profile: &f%world%"
    - "&eEntity count: &f%entity_count%"
    - "&ePlayer count: &f%player_count%"
    - "&eView distance: &f%view_distance%"
    - "&eSimulation distance: &f%sim_distance%"
    - "&eLoaded chunks count: &f%loaded_chunks_count%"
  cpu-overloaded: "&cCPU load more than 90%! Server is lagging!"
  ram-clogged: "&cRAM usage is clogged! Please, clear the RAM or restart the server!"